version: "3.9"

services:
  clinic-scraper:
    build: .
    container_name: clinic-scraper
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python app/main.py --query "Dentist in Maadi"
